db:
  connection: 'jdbc:hsqldb:mem:testdb-application;create=true;user=airline;password=airline'
  driver: 'org.hsqldb.jdbcDriver'
  dialect: 'org.hibernate.dialect.HSQLDialect'
  user: 'airline'
  pass: 'airline'
  schema: 'public'

