<!DOCTYPE html>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<html lang="en">

<body>
    <%--<h1>${message}</h1>--%>

    <%--<spring:url value="/test.txt" htmlEscape="true" var="springUrl" />--%>

    <%--<p><a href="${springUrl}">URL generated by Spring</a></p>--%>

{
    "Destination":{
    "GET /destination": "Return list of all destinations.",
    "POST /destination": "Crete new destination and return its id.",
    "GET /destination/{id}": "Return destination with given id.",
    "PUT /destination/{id}": "Update destination with given id.",
    "DELETE /destination/{id}": "Delete destination with given id."
    },
    "Flight": {
    "GET /flight": "Return list of all flights.",
    "POST /flight": "Crete new flight and return its id.",
    "GET /flight/{id}": "Return flight with given id.",
    "PUT /flight/{id}": "Update flight with given id.",
    "DELETE /flight/{id}": "Delete flight with given id."
    },
    "Reservation", {
    "GET /reservation": "Return list of all reservations.",
    "POST /reservation": "Crete new reservation and return it with id and password filled.",
    "GET /reservation/{id}": "Return reservation with given id.",
    "PUT /reservation/{id}": "Update reservation with given id.",
    "DELETE /reservation/{id}": "Delete reservation with given id."
    }
}
</body>

</html>