
package cz.cvut.fel.aos.printclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PrintingService", targetNamespace = "http://service.printing.aos.fel.cvut.cz/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PrintingService {


    /**
     * 
     * @param jsonstring
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "print", targetNamespace = "http://service.printing.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.printclient.Print")
    @ResponseWrapper(localName = "printResponse", targetNamespace = "http://service.printing.aos.fel.cvut.cz/", className = "cz.cvut.fel.aos.printclient.PrintResponse")
    @Action(input = "http://service.printing.aos.fel.cvut.cz/PrintingService/printRequest", output = "http://service.printing.aos.fel.cvut.cz/PrintingService/printResponse")
    public String print(
        @WebParam(name = "jsonstring", targetNamespace = "")
        String jsonstring);

}
