
package cz.cvut.fel.aos.printclient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PrintingService", targetNamespace = "http://service.printing.aos.fel.cvut.cz/", wsdlLocation = "http://localhost:8080/PrintingService/PrintingService?WSDL")
public class PrintingService_Service
    extends Service
{

    private final static URL PRINTINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRINTINGSERVICE_EXCEPTION;
    private final static QName PRINTINGSERVICE_QNAME = new QName("http://service.printing.aos.fel.cvut.cz/", "PrintingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/PrintingService/PrintingService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRINTINGSERVICE_WSDL_LOCATION = url;
        PRINTINGSERVICE_EXCEPTION = e;
    }

    public PrintingService_Service() {
        super(__getWsdlLocation(), PRINTINGSERVICE_QNAME);
    }

    public PrintingService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRINTINGSERVICE_QNAME, features);
    }

    public PrintingService_Service(URL wsdlLocation) {
        super(wsdlLocation, PRINTINGSERVICE_QNAME);
    }

    public PrintingService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRINTINGSERVICE_QNAME, features);
    }

    public PrintingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PrintingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PrintingService
     */
    @WebEndpoint(name = "PrintingServicePort")
    public PrintingService getPrintingServicePort() {
        return super.getPort(new QName("http://service.printing.aos.fel.cvut.cz/", "PrintingServicePort"), PrintingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PrintingService
     */
    @WebEndpoint(name = "PrintingServicePort")
    public PrintingService getPrintingServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.printing.aos.fel.cvut.cz/", "PrintingServicePort"), PrintingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRINTINGSERVICE_EXCEPTION!= null) {
            throw PRINTINGSERVICE_EXCEPTION;
        }
        return PRINTINGSERVICE_WSDL_LOCATION;
    }

}
